apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: myapp1-deployment-v2
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: myapp1-v2
  template:  
    metadata: # Dictionary
      name: myapp1-pod-v2
      labels: # Dictionary
        app: myapp1-v2  # Key value pairs
    spec:
      containers: # List
        - name: myapp1-container-v2
          image: ghcr.io/nholuongut/kubenginx:2.0.0
          ports: 
            - containerPort: 80  
          resources:
            requests:
              memory: "256Mi" # 128 MebiByte is equal to 135 Megabyte (MB)
              cpu: "250m" # `m` means milliCPU
            limits:
              memory: "512Mi"
              cpu: "400m"  # 1000m is equal to 1 VCPU core                                               
            