kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: app3-default-route
spec:
  parentRefs:
  - kind: Gateway
    name: mygateway1-regional
    sectionName: https
  rules:
  - backendRefs:
    - name: myapp3-service
      port: 80               