apiVersion: apps/v1
kind: Deployment  
metadata: # Dictionary
  name: myapp1-deployment
spec: # Dictionary
  replicas: 2
  selector: 
    matchLabels: 
      app: myapp1
  template:
    metadata: # Dictionary
      name: myapp1-pod
      labels:
        app: myapp1 # Key Value Pairs   
    spec:
      containers: # List
        - name: myapp1-container
          image: ghcr.io/nholuongut/kubenginx:1.0.0
          ports: 
            - containerPort: 80          